apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-backend
  namespace: sms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-backend
  template:
    metadata:
      labels:
        app: sms-backend
    spec:
      containers:
        - name: backend
          image: 048844500645.dkr.ecr.ap-northeast-2.amazonaws.com/sms-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: sms-config
            - secretRef:
                name: sms-secret
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
